stages:
- deploy

Deploy to Heroku:
  stage: deploy
  only:
  - main
  script:
  - git remote add heroku "https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git"
  - git push -f heroku master
